#server:
#  port: 8761
#  ssl:
#      enabled: true
#     client-auth: need
#      key-store: classpath:discovery-cert.jks
#      key-store-password: India330$$
#      keyStoreType: JKS
#      keyStoreProvider: SUN
#      keyAlias: discovery-cert
#      trust-store: classpath:discovery-cert.jks
#      trust-store-password: India330$$
#      trust-store-type: JKS
eureka:
#  instance:
#    nonSecurePortEnabled: false
#    securePortEnabled: true
#    securePort: ${server.port}
#    statusPageUrl: http://localhost:${server.port}/info
#    healthCheckUrl: http://localhost:${server.port}/health
#    homePageUrl: http://localhost:${server.port}
  client:
#    securePortEnabled: true
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#for deploying the applcation on tomcat, below is the url for eureka server
       defaultZone: http://localhost:8080/spring-discovery-service-war/eureka